tap "homebrew/bundle"
tap "nikitabobko/tap"
brew "mas"
cask "aerospace"
cask "figma"
cask "font-iosevka"
cask "ghostty"
cask "karabiner-elements"
cask "raycast"
cask "telegram"
cask "the-unarchiver"
cask "tower"
cask "vlc"
cask "zed"
cask "zoom"
mas "Photomator", id: 1444636541
mas "Xcode", id: 497799835
